#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output HDMI-1 --mode 1920x1080 --rate 144.00
nitrogen --restore &
picom --experimental-backend &
xsetroot -cursor_name left_ptr &
setxkbmap -model pc105 -layout us,ru -variant qwerty -option grp:alt_shift_toggle
bspc monitor -d I II III IV V VI
#conky &
#sh ~/Content/Wallpapers/wallpaper.sh &
#bg-scale
feh --bg-scale --randomize ~/Content/Wallpapers/unsigned/*
polybar &
spotify-listener &
disown

bspc config border_width         0
bspc config window_gap          11

bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bspc config focused_border_color "#f9f8fe"

#ЦВЕТ ПРОСТРАНСТВА ПРИ ВЫБОРЕ ПОЛОЖЕНИЯ НОВОГО ОКНАЫ
bspc config presel_feedback_color "fd2e59"

#ПРИ ПОМОЩИ ЭТОЙ ХРЕНИ МОЖНО СДЕЛАТЬ ГАПСЫ ТОЛЬКО МЕЖДУ ОКНАМИ
#bspc config window_gap $gap;
#bspc config top_padding -$(($gap+2))
#bspc config left_padding -$(($gap+2))
#bspc config right_padding -$(($gap+4))
#bspc config bottom_padding $(($PANEL_HEIGHT-$gap))



#КОФИЦИЕНТ РАЗДЕЛЕНИЯ, СКОЛЬКО ПРОЦЕНТОВ ОСТАНЕТСЯ ОТ РОДИТЕЛЬСКОГО ОКНА ПРИ ОТКРЫТИИ НОВОГО
bspc config split_ratio          0.5
#ФОКУС ОКНА НАВЕДЕНИЕМ КУРСОРА
bspc config focus_follows_pointer true
bspc config pointer_modifier	super

#РЕЖИМ МОНОКЛЯ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config single_monocle	     false

#ОТКЛЮЧЕНИЕ ГАПСОВ РАМОК И ОТСТУПОВ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle	 true


#СХЕМЫ СОГЛАСНО КОТОРЫМ БУДУТ ОТКРЫВАТСЯ ОКНА
#bspc config automatic_scheme	spiral


#ПРАВИЛА ОКОН
bspc rule -a kitty follow=on focus=on #desktop='^1' 

bspc rule -a google-chrome-stable follow=on focus=on rectangle=1350x900+50+90 desktop='^1'

bspc rule -a telegram-desktop follow=on focus=on desktop='^2'
bspc rule -a telegram-desktop follow=on focus=on rectangle=420x900+1450+90 desktop='^2'
bspc rule -a vscodium follow=on focus=on desktop='^2'

bspc rule -a spotify follow=on focus=ondesktop='^3'
bspc rule -a naulius follow=on focus=ondesktop='^2'
bspc rule -a subl follow=on focus=on desktop='^3'
bspc rule -a sublime-text-4 follow=on focus=on desktop='^3'

bspc rule -a Steam state=floating follow=off rectangle=1350x900+285+90 desktop='^4' 
bspc rule -a mpv state=floating rectangle=800x450+560+315 follow=off
bspc rule -a dmenu rectangle=900x22+610+90
bspc rule -a Media viewer rectangle=1350x900+285+90 state=floating


#bspc rule -a conky state=floating border=off

#bspc config border_width         2
#bspc config window_gap          12

#bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
